- name: creating dir
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Ansible check directory.
    stat:
     path: /home/centos
    register: bhanunaidu

  - name: "echo if directory already existed"
    debug:
      msg: "the bhanunaidu directory is already existed"
    when: bhanunaidu.stat.exists

  - name: "Ansible Create directory if not exists"
    become: yes
    file:
     path: /home/centos
     state: directory
     mode: 0755
     group: root
     owner: root
    when: bhanunaidu.stat.exists == false